SalesLT/Controllers/SalesController.cs
using SalesLT.Repositories;
using SalesLT.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SalesLT.Controllers
{
    public class SalesController : Controller
    {
        private readonly SalesService _service;

        public SalesController()
        {
            _service = new SalesService(new SalesRepository(new SalesContext()));
        }
        // GET: Sales
        public ActionResult Index()
        {
            return View(_service.GetCustomers());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            _service.CreateCustomer(customer);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult GetCustomerById(int id)
        {
            return View("Edit", _service.GetCustomerById(id));
        }

        //[HttpPost, ActionName("DeleteCustomer")]
        public ActionResult DeleteCustomer(int id)
        {
            _service.DeleteCustomer(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateCustomer(Customer customer)
        {
            _service.UpdateCustomer(customer);
            return RedirectToAction("Index");
        }
    }
}

SalesLT/Views/Sales/Create.cshtml
@using SalesLT.Repositories

@model Customer

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-lg-12">
        <h2>@ViewBag.Title</h2>
    </div>
</div>

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                @Html.LabelFor(Model => Model.FirstName, "First Name", new { })
                @Html.EditorFor(Model => Model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.MiddleName, "Middle Name", new { })
                @Html.EditorFor(Model => Model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.LastName, "Last Name", new { })
                @Html.EditorFor(Model => Model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.EmailAddress, "Email Address", new { })
                @Html.EditorFor(Model => Model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.Phone, "Phone", new { })
                @Html.EditorFor(Model => Model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                @Html.LabelFor(Model => Model.CustomerAddresses[0].Address.AddressLine1, "Address", new { })
                @Html.EditorFor(Model => Model.CustomerAddresses[0].Address.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.CustomerAddresses[0].Address.AddressLine2, "Apt/Suite", new { })
                @Html.EditorFor(Model => Model.CustomerAddresses[0].Address.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.CustomerAddresses[0].Address.City, "City", new { })
                @Html.EditorFor(Model => Model.CustomerAddresses[0].Address.City, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.CustomerAddresses[0].Address.StateProvince, "State", new { })
                @Html.EditorFor(Model => Model.CustomerAddresses[0].Address.StateProvince, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.CustomerAddresses[0].Address.CountryRegion, "Country", new { })
                @Html.EditorFor(Model => Model.CustomerAddresses[0].Address.CountryRegion, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.CustomerAddresses[0].Address.PostalCode, "ZIP", new { })
                @Html.EditorFor(Model => Model.CustomerAddresses[0].Address.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <input type="submit" value="Add Customer" class="btn btn-primary" />
        </div>
    </div>
}

SalesLT/Views/Sales/Edit.cshtml
@using SalesLT.Repositories;
@model  Customer

@{
    ViewBag.Title = "Edit Customer";
}

<div class="row">
    <div class="col-lg-12">
        <h2>@ViewBag.Title</h2>
    </div>
</div>

@using (Html.BeginForm("UpdateCustomer", "Sales"))
{
    <div class="row">
        @Html.HiddenFor(Model => Model.Id)
        <div class="col-lg-4">
            <h3>Customer Information</h3>
            <div class="form-group">
                @Html.LabelFor(Model => Model.FirstName, "First Name", new { })
                @Html.EditorFor(Model => Model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.MiddleName, "Middle Name", new { })
                @Html.EditorFor(Model => Model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.LastName, "Last Name", new { })
                @Html.EditorFor(Model => Model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.EmailAddress, "Email Address", new { })
                @Html.EditorFor(Model => Model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <div class="form-group">
                @Html.LabelFor(Model => Model.Phone, "Phone", new { })
                @Html.EditorFor(Model => Model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="col-lg-4">
            @for (int i = 0; i < Model.CustomerAddresses.Count(); i++)
            {
                var addressNumber = 1;
                addressNumber = addressNumber + i;
                <h3>Address @addressNumber</h3>
                @Html.HiddenFor(Model => Model.CustomerAddresses[i].Address.AddressId)
                <div class="form-group">
                    @Html.LabelFor(Model => Model.CustomerAddresses[i].Address.AddressLine1, "Address", new { })
                    @Html.EditorFor(Model => Model.CustomerAddresses[i].Address.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.CustomerAddresses[i].Address.AddressLine2, "Apt/Suite", new { })
                    @Html.EditorFor(Model => Model.CustomerAddresses[i].Address.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.CustomerAddresses[i].Address.City, "City", new { })
                    @Html.EditorFor(Model => Model.CustomerAddresses[i].Address.City, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.CustomerAddresses[i].Address.StateProvince, "State", new { })
                    @Html.EditorFor(Model => Model.CustomerAddresses[i].Address.StateProvince, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.CustomerAddresses[i].Address.CountryRegion, "Country", new { })
                    @Html.EditorFor(Model => Model.CustomerAddresses[i].Address.CountryRegion, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => Model.CustomerAddresses[i].Address.PostalCode, "ZIP", new { })
                    @Html.EditorFor(Model => Model.CustomerAddresses[i].Address.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            }

            <button class="btn btn-success btn-sm">+ Add Address</button>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            @Html.ActionLink("Back", "Index", "Sales", new object { }, new { @class = "btn btn-link" })
            <input type="submit" value="Update Customer" class="btn btn-primary" />
        </div>
    </div>
}

SalesLT/Views/Sales/Index.cshtml
@using SalesLT.Repositories;
@model List<Customer>

<div class="row">
    <div class="col-lg-4">
        <h2>Customer</h2>

        <ul class="list-group">
        @foreach (var customer in Model)
         {
            <li class="list-group-item">
                @customer.FirstName @customer.MiddleName @customer.LastName

                @Html.ActionLink("Delete", "DeleteCustomer", "Sales", new { id = customer.Id }, new { @class = "badge badge-secondary" })

                @Html.ActionLink("Edit", "GetCustomerById", "Sales", new { id = @customer.Id }, new { @class = "badge badge-secondary"})
            </li>
         }
        </ul>

    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        @Html.ActionLink("Add Customer", "Create", "Sales", new object { }, new { @class = "btn btn-primary" })
    </div>
</div>